### ISSUE TITLE
Couldn't convert HEIC to JPG: '' | Bin used: 'heicToJpg' HEIC: 'explain.heic'

### ISSUE THREAD

**Issue by AppDevZoneOff** [MaestroError/php-heic-to-jpg#8]
hi there.
i m facing this error on this lib.
can explain or guide me how can i fix this.

Couldn't convert HEIC to JPG: '' | Bin used: 'heicToJpg' HEIC: 'file.com/sample1.heic' Full Command: '/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg "file.com/sample1.heic" "file.com/sample1.heic-1909936596641d3c86bc59c0.67921754"'

and i am using laravel 

Thank you.....

**Comment by MaestroError** [comment]
Hello @AppDevZoneOff! Thank you for the feedback, I think the issue is related to the connection, the tool can't access the web and download images from it, converting images should exist on your filesystem 👍 So you can download a file using PHP as described in [this answer](https://stackoverflow.com/questions/724391/saving-image-from-php-url), then convert it using `heicToJpg` and remove original HEIC file (of course, if you don't need it anymore)

**Comment by yuanxin32323** [comment]
I have encountered this situation as well. I am dealing with a local file, and the following is the error message.

Couldn't convert HEIC to JPG: '' | Bin used: 'heicToJpg' HEIC: '/www/wwwroot/www.mishejia.com/public/uploads/image/20230327/6e09410efcc200d2ab6f99ce705c86a7.HEIC' Full Command: '/www/wwwroot/www.mishejia.com/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg "/www/wwwroot/www.mishejia.com/public/uploads/image/20230327/6e09410efcc200d2ab6f99ce705c86a7.HEIC" "/www/wwwroot/www.mishejia.com/public/uploads/image/20230327/6e09410efcc200d2ab6f99ce705c86a7.HEIC-1769820766421a9c782d929.90318565"'

**Comment by MaestroError** [comment]
@AppDevZoneOff New [convertFromUrl](https://github.com/MaestroError/php-heic-to-jpg#convertfromurl-method) method added 👍
